model: default

pretrain: True
pretrain_path: './weights/dgg-hmr/dgg_672_vitb.pth'

eval_datasets_used: ['mupots']
eval_datasets_split: ['test']

eval_vis_num: 20
conf_thresh: [0.1, 0.2, 0.3]
eval_batch_size: 8
eval_num_workers: 12
distributed_eval: True
